remote_theme: pages-themes/minimal@v0.2.0

title: Розробка вебсайту закладу харчування

description: Дипломна робота Свинаренка А.О.

# Розробка вебсайту закладу харчування

Кваліфікаційна робота на підтвердження ступеня фахового молодшого
бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)). Керівник
роботи – **Кривцова Олена Павлівна**.

## Завдання до дипломної роботи

Розроблений програмний продукт має надавати всю необхідну функціональністб, яка включає можливості формування онлайн-замовлення, вибір між онлайн оплатою і розрахунком готівкою. Особливу увагу слід звернути на аналіз аналогічних продуктів, дослідження предметної області завдання та вимог користувачів. Засоби розробки - HTML, CSS, JS, PHP. Розроблений вебдодаток та його структура мають бути детально описані у пояснювальній записці.

## Використані технології

- HTML – створення розмітки та структури сторінки;
- CSS – візуальна презентація сторінки;
- JS – функціональна взаємодія елементів сторінки;
- PHP - реалізація інтерактивності сторінки;

## Опублікований продукт
Створена вебсторінка представлена за посиланням
[]()
